version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - pgvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  scheduler:
    build:
      dockerfile: Dockerfile
      context: ./scheduler
    restart: always
    volumes:
      - /app/node_modules
      - ./scheduler:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - client
      - api
    ports:
      - "80:80"
volumes:
  pgvol:
