version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - PGUSER=skellie123
      - PGHOST=grimm123
      - PGDATABASE=yieldanalyzer
      - PGPASSWORD=123skullingham
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=skellie123
      - PGHOST=grimm123
      - PGDATABASE=yieldanalyzer
      - PGPASSWORD=123skullingham
      - PGPORT=5432
  scheduler:
    build:
      dockerfile: Dockerfile.dev
      context: ./scheduler
    volumes:
      - /app/node_modules
      - ./scheduler:/app
    environment:
      - PGUSER=skellie123
      - PGHOST=grimm123
      - PGDATABASE=yieldanalyzer
      - PGPASSWORD=123skullingham
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
